# Generated by Django 3.1 on 2020-08-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cassette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('subjects', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('year_of_release', models.DateTimeField()),
                ('film_studio', models.CharField(max_length=45)),
                ('count', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.seller')),
            ],
        ),
        migrations.CreateModel(
            name='CassetteInSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('cassette_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cassette')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sale')),
            ],
        ),
        migrations.CreateModel(
            name='CassetteInAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('admission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.admission')),
                ('cassette_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cassette')),
            ],
        ),
        migrations.AddField(
            model_name='cassette',
            name='in_admission',
            field=models.ManyToManyField(through='shop.CassetteInAdmission', to='shop.Admission'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='in_sale',
            field=models.ManyToManyField(through='shop.CassetteInSale', to='shop.Sale'),
        ),
        migrations.AddField(
            model_name='admission',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.seller'),
        ),
    ]
