# Generated by Django 3.1 on 2020-08-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200824_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='CassetteInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(default=0)),
                ('date', models.DateTimeField(null=True)),
                ('bought', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.seller')),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller_id',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='cassetteinadmission',
            old_name='admission_id',
            new_name='admission',
        ),
        migrations.RenameField(
            model_name='cassetteinadmission',
            old_name='cassette_id',
            new_name='cassette',
        ),
        migrations.RemoveField(
            model_name='cassette',
            name='in_sale',
        ),
        migrations.DeleteModel(
            name='CassetteInSale',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AddField(
            model_name='cassetteinorder',
            name='cassette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cassette'),
        ),
        migrations.AddField(
            model_name='cassetteinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='in_order',
            field=models.ManyToManyField(through='shop.CassetteInOrder', to='shop.Order'),
        ),
    ]
