# Generated by Django 3.1 on 2020-09-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cassette',
            name='in_admission',
        ),
        migrations.AddField(
            model_name='admission',
            name='cassette',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.cassette'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='CassetteInAdmission',
        ),
    ]
