version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=finpro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4ervya40k
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
