# Generated by Django 3.0.3 on 2020-02-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carMake', models.CharField(max_length=30)),
                ('carModel', models.CharField(max_length=30)),
                ('prodYear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, db_column = 'firstName')),
                ('lastName', models.CharField(max_length=30, db_column = 'lastName')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, db_column = 'sex')),
                ('idNumber', models.CharField(max_length=30, db_column = 'idNumber')),
            ],
        ),
        migrations.CreateModel(
            name='dLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlNum', models.CharField(max_length=30, db_column = 'dlNum')),
                ('type', models.CharField(choices=[('F', 'Foreign'), ('N', 'Native')], max_length=1, db_column = 'type')),
                ('someKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belov.User', db_column = 'someKey')),
            ],
        ),
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(db_column = 'startDate')),
                ('endDate', models.DateField(db_column = 'endDate')),
                ('automobile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belov.Car', db_column = 'automobile')),
                ('human_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belov.User', db_column = 'human')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='dates',
            field=models.ManyToManyField(through='belov.CarUser', to='belov.User'),
        ),
    ]
