# Generated by Django 3.1.3 on 2020-11-04 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patrolling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('area_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('boat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navalpolice.boat')),
            ],
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrol_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('exp', models.IntegerField()),
                ('age', models.IntegerField()),
                ('boat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navalpolice.boat')),
            ],
        ),
    ]
