# Generated by Django 3.1.3 on 2020-11-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navalpolice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='boat_id',
        ),
        migrations.RemoveField(
            model_name='patrol',
            name='patrol_id',
        ),
        migrations.AlterField(
            model_name='boat',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patrol',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
