# Generated by Django 3.0.4 on 2020-03-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samoletov_app', '0002_auto_20200325_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='users',
            new_name='cars',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='cars',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='users',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='gender',
        ),
        migrations.AddField(
            model_name='car',
            name='number',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
    ]
