# Generated by Django 3.1.2 on 2020-10-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('Train_ID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('TrainName', models.CharField(db_index=True, max_length=150)),
                ('TrainType', models.CharField(db_index=True, max_length=150)),
                ('carCount', models.IntegerField(db_index=True, max_length=150)),
                ('ScheduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway.schedule')),
            ],
        ),
    ]
