# Generated by Django 3.1.2 on 2020-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0002_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='carCount',
            field=models.IntegerField(db_index=True),
        ),
    ]
