# Generated by Django 3.1.2 on 2020-10-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0003_auto_20201010_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost', models.PositiveIntegerField()),
                ('Train_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway.train')),
            ],
        ),
    ]
