# Generated by Django 3.1.2 on 2020-10-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0004_traincost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traincost',
            name='id',
        ),
        migrations.AlterField(
            model_name='traincost',
            name='Cost',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('Ticket_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway.traincost')),
                ('ScheduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway.schedule')),
                ('Train_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Railway.train')),
            ],
        ),
    ]
