# Generated by Django 3.1.2 on 2020-10-14 03:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.IntegerField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.IntegerField()),
                ('flight_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crew')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Heli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heli_id', models.IntegerField()),
                ('mark', models.CharField(max_length=50)),
                ('prod_date', models.DateField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('user_id', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Lux', 'Lux'), ('Normal', 'Normal'), ('Budget', 'Budget')], max_length=50)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot_id', models.IntegerField()),
                ('surname', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crew')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='heli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.heli'),
        ),
    ]
