# Generated by Django 3.0.3 on 2020-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platonov_app', '0002_drive_lic'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='drivers',
            field=models.ManyToManyField(to='platonov_app.auto'),
        ),
    ]
