# Generated by Django 3.1.1 on 2020-09-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=45, verbose_name='Марка')),
                ('model', models.CharField(max_length=45, verbose_name='Модель')),
                ('color', models.CharField(max_length=45, verbose_name='Цвет')),
                ('pub_year', models.DateField(max_length=4, verbose_name='Год выпуска')),
                ('date_reg', models.DateField(verbose_name='Дата регистрации')),
                ('license_plate', models.CharField(max_length=6, verbose_name='Номер')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_driver', models.CharField(max_length=100, verbose_name='ФИО водителя')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('license_number', models.IntegerField(max_length=10, unique=True, verbose_name='Водительское удостоверение')),
                ('address', models.CharField(max_length=45, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_inspector', models.CharField(max_length=100, verbose_name='ФИО инспектора')),
                ('num_inspector', models.CharField(max_length=10, unique=True, verbose_name='Номер сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='Нарушение')),
                ('fine', models.IntegerField(verbose_name='Штраф')),
                ('term_deprivation', models.IntegerField(verbose_name='Срок лишения прав')),
            ],
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_judgement', models.DateField(verbose_name='Дата нарушения')),
                ('time_judgement', models.TimeField(verbose_name='Время нарушения')),
                ('area', models.CharField(max_length=45, verbose_name='Район')),
                ('car', models.ManyToManyField(to='gai_app.Car', verbose_name='Автомобиль')),
                ('inspector', models.ManyToManyField(to='gai_app.Inspector', verbose_name='Инспектор')),
                ('offence', models.ManyToManyField(to='gai_app.Offence', verbose_name='Нарушение')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ManyToManyField(to='gai_app.Driver', verbose_name='Водитель'),
        ),
    ]
