# Generated by Django 3.1.2 on 2020-10-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='lic_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
