# Generated by Django 3.1.2 on 2020-10-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0002_auto_20201013_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='id_contract',
            new_name='id_contract',
        ),
    ]
