# Generated by Django 3.1.2 on 2020-10-06 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinshoppingbag',
            name='counter',
        ),
        migrations.AddField(
            model_name='productinshoppingbag',
            name='date_of_adding',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productinshoppingbag',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
