# Generated by Django 3.1.2 on 2020-10-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201006_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinshoppingbag',
            name='session',
        ),
    ]
