# Generated by Django 3.1.2 on 2020-10-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_productinshoppingbag_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinshoppingbag',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.clientuser'),
            preserve_default=False,
        ),
    ]
