# Generated by Django 3.1.2 on 2020-10-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201006_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinshoppingbag',
            name='client',
        ),
        migrations.AddField(
            model_name='productinshoppingbag',
            name='shopping_bag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.shoppingbag'),
            preserve_default=False,
        ),
    ]
