# Generated by Django 3.1.2 on 2020-10-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201006_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinshoppingbag',
            name='shopping_bag',
        ),
        migrations.AddField(
            model_name='productinshoppingbag',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.clientuser'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShoppingBag',
        ),
    ]
