# Generated by Django 3.1.1 on 2020-09-30 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrol_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_patrol', models.DateField(verbose_name='Дата патрулирования')),
                ('vilorators_number', models.IntegerField(verbose_name='Количество нарушителей')),
            ],
        ),
        migrations.CreateModel(
            name='Patrolman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('position', models.CharField(max_length=40, verbose_name='Должность')),
                ('begin_work', models.DateField(null=True, verbose_name='Дата начала работы')),
                ('date_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('experience', models.IntegerField(null=True, verbose_name='Стаж')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Patrolman_has_patrol_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_boat', models.IntegerField(verbose_name='Номер катера')),
                ('id_patrol_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='see_police.patrol_result', verbose_name='Номер патрулирования')),
                ('service_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='see_police.patrolman', verbose_name='Номер патрульного')),
            ],
        ),
        migrations.CreateModel(
            name='Patrol_water_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_area', models.IntegerField(verbose_name='Номер участка акватории')),
                ('id_patrol_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='see_police.patrol_result', verbose_name='Номер патрулирования')),
            ],
        ),
    ]
