# Generated by Django 3.0.3 on 2020-02-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('prod_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('pass_num', models.IntegerField(max_length=10)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('license_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nikolaev_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='AutoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nikolaev_app.Auto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nikolaev_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='many_to_many_field',
            field=models.ManyToManyField(through='nikolaev_app.AutoUser', to='nikolaev_app.User'),
        ),
    ]
