# Generated by Django 3.0.3 on 2020-05-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belov', '0002_somemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caruser',
            name='automobile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belov.Car'),
        ),
        migrations.AlterField(
            model_name='caruser',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='caruser',
            name='human_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belov.User'),
        ),
        migrations.AlterField(
            model_name='caruser',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dlicense',
            name='dlNum',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dlicense',
            name='someKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belov.User'),
        ),
        migrations.AlterField(
            model_name='dlicense',
            name='type',
            field=models.CharField(choices=[('F', 'Foreign'), ('N', 'Native')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='idNumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
