# Generated by Django 3.0.8 on 2020-07-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_buy', models.DateField()),
                ('date_Sell', models.DateField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platonov_app.auto')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('secondName', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('driver', models.ManyToManyField(through='platonov_app.Drivers', to='platonov_app.auto')),
            ],
        ),
        migrations.AddField(
            model_name='drivers',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platonov_app.users'),
        ),
        migrations.CreateModel(
            name='drive_lic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('RF', 'Russia'), ('I', 'International')], max_length=2)),
                ('date_get', models.DateField()),
                ('date_end', models.DateField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platonov_app.users')),
            ],
        ),
    ]
