# Generated by Django 3.0.7 on 2020-10-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew_member',
            name='category',
            field=models.CharField(max_length=45, verbose_name='category'),
        ),
    ]
