# Generated by Django 3.1.2 on 2020-10-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=88)),
                ('broker_addr', models.CharField(max_length=88)),
                ('broker_dob', models.DateField()),
            ],
        ),
    ]
