# Generated by Django 3.0.5 on 2020-04-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=88)),
                ('last_name', models.CharField(max_length=88)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Machina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_made', models.CharField(max_length=88)),
                ('car_model', models.CharField(max_length=88)),
                ('colour', models.CharField(max_length=88)),
                ('govnum', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.IntegerField(default=9031993)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('license_type', models.CharField(choices=[('A', 'A'), ('A1', 'A1'), ('B', 'B'), ('B1', 'B1'), ('BE', 'BE'), ('C', 'C'), ('C1', 'C1'), ('CE', 'CE'), ('C1E', 'C1E'), ('D', 'D'), ('D1', 'D1'), ('DE', 'DE'), ('D1E', 'D1E'), ('M', 'M'), ('Tm', 'Tm'), ('Tb', 'Tb')], max_length=3)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Deus')),
            ],
        ),
        migrations.CreateModel(
            name='ExMachina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_opened', models.DateField()),
                ('ownership_closed', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Machina')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Deus')),
            ],
        ),
    ]
