# Generated by Django 3.0.5 on 2020-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exmachina',
            name='car',
        ),
        migrations.AddField(
            model_name='exmachina',
            name='car',
            field=models.ManyToManyField(to='project_first_app.Machina'),
        ),
        migrations.RemoveField(
            model_name='exmachina',
            name='owner',
        ),
        migrations.AddField(
            model_name='exmachina',
            name='owner',
            field=models.ManyToManyField(to='project_first_app.Deus'),
        ),
    ]
