# Generated by Django 3.0.7 on 2020-06-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20200607_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('A', 'motorcycle'), ('B', 'car'), ('C', 'truck'), ('D', 'bus')], max_length=1),
        ),
    ]
