# Generated by Django 3.0.7 on 2020-06-10 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_car_possession'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
