# Generated by Django 3.0.7 on 2020-06-10 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_owner_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='date_of_issue',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='possession',
            name='date_of_end',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='possession',
            name='date_of_start',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
