# Generated by Django 2.2.10 on 2020-11-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voznesensky_app', '0002_auto_20201103_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_place',
            field=models.CharField(blank=True, max_length=45, verbose_name='Место рождения'),
        ),
    ]
