# Generated by Django 3.0.6 on 2020-06-28 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busName', models.TextField(verbose_name='Название автобуса')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('busType', models.CharField(choices=[('D', 'Bus'), ('DE', 'Bus with trailer'), ('D1', 'Small bus'), ('D1E', 'Small bus with trailer')], max_length=3, verbose_name='Тип прав')),
                ('busNumber', models.CharField(default='A111', max_length=4, verbose_name='Номер автобуса')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобусы',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.TextField(verbose_name='Название маршрута')),
                ('startCity', models.TextField(verbose_name='Город отправления')),
                ('finishCity', models.TextField(verbose_name='Город прибытия')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Протяженность маршрута')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления')),
                ('dateFinish', models.DateTimeField(auto_now_add=True, verbose_name='Дата прибытия')),
                ('amount', models.PositiveIntegerField(max_length=2, verbose_name='Количество пассажиров')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена билета')),
                ('state', models.CharField(choices=[('R', 'Ready'), ('D', 'Done'), ('C', 'Cancelled')], max_length=1, verbose_name='Состояние')),
                ('raceBus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_work_app.Bus', verbose_name='Автобус маршрута')),
                ('raceRoute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_work_app.Route', verbose_name='Маршрут отправки')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.TextField(blank=True, verbose_name='ФИО')),
                ('location', models.TextField(blank=True, verbose_name='Адрес')),
                ('birth_date', models.DateField(auto_now_add=True, verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(verbose_name='Стаж')),
                ('category', models.CharField(choices=[('D', 'Bus'), ('DE', 'Bus with trailer'), ('D1', 'Small bus'), ('D1E', 'Small bus with trailer')], max_length=3, verbose_name='Категория')),
                ('driverBus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_work_app.Bus', verbose_name='Автобус водителя')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_work_app.Profile', verbose_name='Гражданин')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
    ]
