# Generated by Django 3.0.6 on 2020-06-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_work_app', '0002_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='race',
            name='dateFinish',
            field=models.DateField(blank=True, verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='race',
            name='dateStart',
            field=models.DateField(blank=True, verbose_name='Дата отправления'),
        ),
    ]
