# Generated by Django 3.0.6 on 2020-06-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_work_app', '0003_auto_20200629_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
    ]
