# Generated by Django 3.0.7 on 2020-06-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field_of_activity', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100)),
                ('busy_time', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('desired_salary', models.IntegerField()),
                ('date_of_application', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100)),
                ('busy_time', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('information', models.TextField()),
                ('date_of_application', models.DateTimeField(auto_now_add=True)),
                ('id_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employer')),
            ],
        ),
    ]
