# Generated by Django 3.0.7 on 2020-06-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='id_job_seeker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Job_seeker'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='id_employer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Employer'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=50)),
                ('date_of_application', models.DateTimeField(auto_now_add=True)),
                ('id_summary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Summary')),
                ('id_vacancy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Vacancy')),
            ],
        ),
    ]
