# Generated by Django 3.0.7 on 2020-06-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200628_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='information',
            field=models.TextField(default='information'),
        ),
        migrations.AlterField(
            model_name='response',
            name='id_summary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Summary'),
        ),
    ]
