# Generated by Django 3.0.7 on 2020-06-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200629_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job_seeker',
            name='user',
        ),
    ]
