# Generated by Django 3.0.7 on 2020-06-29 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_auto_20200629_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_seeker',
            name='name',
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
