# Generated by Django 3.0.7 on 2020-06-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_employer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.IntegerField(),
        ),
    ]
