# Generated by Django 3.0.3 on 2020-06-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_auto_20200625_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendedusermodel',
            options={'permissions': [('add_voyage', 'You can add voyage as a captain'), ('see_ship_info', 'You can see info about ship'), ('see_award', 'You can see awards'), ('see_fish_op', 'You have access to stock operations'), ('edit_ship_info', 'You have access to ship operations')]},
        ),
    ]
