# Generated by Django 3.0.3 on 2020-06-26 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_auto_20200626_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trawlers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prodDate', models.DateField(default='1970-01-03')),
            ],
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='job_type',
            field=models.CharField(choices=[('CPT', 'captain'), ('SLR', 'sailor'), ('ACC', 'accountant'), ('NUL', '---')], default='sailor', max_length=20),
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField(default='1970-01-03')),
                ('endDate', models.DateField(default='1970-01-03')),
                ('fishQty', models.IntegerField()),
                ('tId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.Trawlers')),
            ],
        ),
        migrations.CreateModel(
            name='FishOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('optType', models.CharField(choices=[('RS', 'restock'), ('SL', 'sell')], max_length=20)),
                ('price', models.IntegerField()),
                ('tId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.Trawlers')),
            ],
        ),
        migrations.CreateModel(
            name='Crews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.Trawlers')),
                ('uId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('awardSize', models.IntegerField()),
                ('date', models.DateField(default='1970-01-03')),
                ('uId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
