# Generated by Django 3.0.3 on 2020-06-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_auto_20200626_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendedusermodel',
            options={'permissions': [('add_voyage', 'You can add voyage as a captain'), ('see_ship_info', 'You can see info about ship'), ('see_award', 'You can see awards'), ('see_fish_op', 'You have access to stock operations'), ('edit_ship_info', 'You have access to ship operations'), ('edit_crews', 'You have access to crew management')]},
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='job_type',
            field=models.CharField(choices=[('', '---'), ('CPT', 'captain'), ('SLR', 'sailor'), ('ACC', 'accountant')], default='sailor', max_length=20),
        ),
    ]
