# Generated by Django 3.0.10 on 2020-10-09 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0002_auto_20201009_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurGathering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=45)),
                ('sort', models.IntegerField()),
                ('count', models.IntegerField()),
                ('id_hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyapp.Hunter')),
            ],
        ),
    ]
