# Generated by Django 2.2.10 on 2020-11-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voznesensky_app', '0003_auto_20201103_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('Д', 'Другой')], default='М', max_length=32),
        ),
    ]
