# Generated by Django 3.0.8 on 2020-07-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0002_auto_20200701_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='slug',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
