# Generated by Django 3.0.8 on 2020-07-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0004_auto_20200702_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='slug',
            field=models.SlugField(max_length=15),
        ),
    ]
