# Generated by Django 3.0.8 on 2020-07-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0006_remove_trips_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
