# Generated by Django 3.1.3 on 2020-11-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crew_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('experience', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('year_of_birth', models.DateField()),
                ('functions', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment_of_the_pilot_on_the_helicopter', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='flight_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField()),
                ('cargo_weight', models.IntegerField()),
                ('number_of_people', models.IntegerField()),
                ('flight_duration', models.TimeField()),
                ('departure', models.CharField(max_length=50)),
                ('arrival', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('id_helicopter', models.IntegerField(blank=True, null=True)),
                ('id_crew_member_1', models.IntegerField(blank=True, null=True)),
                ('id_crew_member_2', models.IntegerField(blank=True, null=True)),
                ('id_crew_member_3', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='helicopter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_helicopter', models.CharField(max_length=50)),
                ('production_date', models.DateField()),
                ('carrying', models.IntegerField()),
                ('date_of_last_repair', models.DateField()),
                ('time_resource_until_the_next_major_overhaul', models.TimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='helicopter_crew_identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment_of_crew_on_the_helicopter', models.DateField()),
            ],
        ),
    ]
