# Generated by Django 3.0.5 on 2020-05-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_auto_20200514_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
