version: '3'
services:
    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        stdin_open: true
        tty: true
        command:
            python manage.py runserver [::]:8000
        ports:
            - 8000:8000
    web:
        build:
            context: ./app-vue
            dockerfile: ./Dockerfile
        environment:
            - PORT=8021
        command: npm run start
        network_mode: host
        ports:
            - 8021:8021
        depends_on:
            - server
