# Generated by Django 3.0.7 on 2020-06-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('client_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('client_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('client_address', models.CharField(blank=True, max_length=30, null=True)),
                ('client_city', models.CharField(blank=True, max_length=30, null=True)),
                ('client_country', models.CharField(choices=[('RU', 'Russia'), ('UKR', 'Ukraine'), ('BLR', 'Belarus')], default='RU', max_length=3)),
                ('client_phone_number', models.IntegerField(blank=True, null=True)),
                ('client_credit_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('employee_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_position', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_address', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_city', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_country', models.CharField(choices=[('RU', 'Russia'), ('UKR', 'Ukraine'), ('BLR', 'Belarus')], default='RU', max_length=3)),
                ('employee_phone_number', models.IntegerField(blank=True, null=True)),
                ('employee_hiring_date', models.DateField()),
                ('employee_birthday_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('category_name', models.CharField(default='default', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('provider_organization', models.CharField(blank=True, max_length=30, null=True)),
                ('provider_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('provider_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('provider_position', models.CharField(blank=True, max_length=30, null=True)),
                ('provider_phone_number', models.IntegerField(blank=True, null=True)),
                ('provider_address', models.CharField(blank=True, max_length=30, null=True)),
                ('provider_city', models.CharField(blank=True, max_length=30, null=True)),
                ('provider_country', models.CharField(choices=[('RU', 'Russia'), ('UKR', 'Ukraine'), ('BLR', 'Belarus')], default='RU', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=30, null=True)),
                ('product_count', models.IntegerField(blank=True, null=True)),
                ('product_cost', models.IntegerField(blank=True, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.ProductCategories')),
                ('product_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateField(default='2020-01-01')),
                ('order_completion_date', models.DateField(blank=True, null=True)),
                ('order_client_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='flower.Clients')),
                ('order_employee_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='flower.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product_count', models.IntegerField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.Orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.Products')),
            ],
            options={
                'unique_together': {('order_id', 'product_id')},
            },
        ),
    ]
