# Generated by Django 3.0.7 on 2020-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_orders',
            field=models.IntegerField(default=0),
        ),
    ]
