# Generated by Django 3.1.2 on 2020-10-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='number',
        ),
    ]
