# Generated by Django 3.1.2 on 2020-10-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20201008_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='school_grades',
            field=models.IntegerField(choices=[(9, 9), (10, 10), (11, 11)], default=9),
        ),
    ]
