# Generated by Django 3.1.2 on 2020-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20201008_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='citizenship',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='parent_phone',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
