# Generated by Django 3.1.2 on 2020-10-08 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20201008_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 18, 55, 29, 334195, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='citizenship',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='parent_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
