# Generated by Django 3.1.2 on 2020-10-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20201008_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
