# Generated by Django 3.1.2 on 2020-10-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20201008_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
