# Generated by Django 3.1.2 on 2020-10-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20201008_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
