# Generated by Django 3.1.1 on 2020-10-06 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
                ('total_games', models.IntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anon_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('genre_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('game_name', models.CharField(max_length=70)),
                ('production_date', models.DateField()),
                ('firm', models.CharField(max_length=70)),
                ('url_screen', models.URLField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('genres', models.ManyToManyField(related_name='games', to='Gameshop.Genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CartGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gameshop.cart')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gameshop.game', verbose_name='Игра')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gameshop.customer')),
            ],
            options={
                'verbose_name': 'Игра в корзине',
                'verbose_name_plural': 'Игры в корзине',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='carts', to='Gameshop.CartGame'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gameshop.customer'),
        ),
    ]
