# Generated by Django 3.1.1 on 2020-10-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gameshop', '0002_auto_20201006_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='1', max_length=100),
        ),
    ]
