# Generated by Django 3.1.2 on 2020-10-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ow_first_name', models.CharField(max_length=88)),
                ('ow_last_name', models.CharField(max_length=88)),
                ('ow_dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_brand', models.CharField(max_length=88)),
                ('veh_model', models.CharField(max_length=88)),
                ('veh_colour', models.CharField(max_length=88)),
                ('veh_plate', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_open', models.DateField()),
                ('ship_close', models.DateField()),
                ('ship_owner', models.ManyToManyField(to='project_first_app.Owner')),
                ('ship_vehicle', models.ManyToManyField(to='project_first_app.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic_no', models.IntegerField()),
                ('lic_date', models.DateField()),
                ('lic_type', models.CharField(choices=[('A', 'A'), ('A1', 'A1'), ('B', 'B'), ('B1', 'B1'), ('BE', 'BE'), ('C', 'C'), ('C1', 'C1'), ('CE', 'CE'), ('C1E', 'C1E'), ('D', 'D'), ('D1', 'D1'), ('DE', 'DE'), ('D1E', 'D1E'), ('M', 'M'), ('Tm', 'Tm'), ('Tb', 'Tb')], max_length=3)),
                ('lic_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.owner')),
            ],
        ),
    ]
