# Generated by Django 3.0.8 on 2020-07-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusNum', models.IntegerField()),
                ('NameB', models.CharField(max_length=15)),
                ('Mileage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('StartP', models.CharField(max_length=45)),
                ('EndP', models.CharField(max_length=45)),
                ('Length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateS', models.DateField()),
                ('DateE', models.DateField()),
                ('Qty', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('FkBusNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turist.Bus')),
                ('FkRoute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turist.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=15)),
                ('Number', models.IntegerField()),
                ('Exp', models.CharField(max_length=45)),
                ('Category', models.CharField(max_length=1)),
                ('Address', models.CharField(max_length=45)),
                ('Birthday', models.DateField()),
                ('FkBusNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turist.Bus')),
            ],
        ),
    ]
