# Generated by Django 3.0.8 on 2020-07-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='BusNum',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='Number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='Name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
