# Generated by Django 3.0.8 on 2020-07-02 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0007_delete_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateS', models.DateField()),
                ('DateE', models.DateField()),
                ('Qty', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('FkBusNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turist.Bus')),
                ('FkRoute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turist.Route')),
            ],
        ),
    ]
