# Generated by Django 3.0.8 on 2020-07-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0009_trips_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='turi',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
